name: Collect Scripts

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  collect-scripts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Step 3: Install dependencies (if needed)
      #- name: Install dependencies
      #  run: |
      #    pip install -r requirements.txt || true

      # Step 4: Run the Python script
      - name: Run collect_scripts.py
        run: |
          python collect_scripts.py

      # Save file in main
      - name: Commit collected_scripts.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add collected_scripts.txt
          git commit -m "Add collected_scripts.txt"
          git push
