name: Ngrok Preview Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: true
        default: "main"

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the specified branch
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Add Missing Plugin and Install Dependencies
      - name: Install Missing Dependencies
        run: |
          npm install @vitejs/plugin-react --save-dev
          npm ci

      # Step 4: Build React App
      - name: Build React App
        run: npm run build

      # Step 5: Start Local Server to Serve the React App
      - name: Start Local Server
        run: |
          npm install -g serve
          serve -s dist -l 5000 &
        env:
          NODE_ENV: production

      # Step 6: Install Ngrok and Expose Local Server
      - name: Install and Run Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list >/dev/null
          sudo apt update && sudo apt install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok http 5000 > ngrok.log &
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      # Step 7: Display the Ngrok Public URL
      - name: Show Ngrok URL
        run: |
          sleep 5
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
