name: Ngrok Preview Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: true
        default: "main"

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the specified branch
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Ensure Dependencies Are Installed
      - name: Ensure Dependencies Are Installed
        run: |
          if ! npm list @vitejs/plugin-react > /dev/null 2>&1; then
            echo "Installing @vitejs/plugin-react..."
            npm install @vitejs/plugin-react --save-dev
          fi
          if [ ! -f package-lock.json ]; then
            echo "Running npm install to generate lock file..."
            npm install
          else
            echo "Using npm ci for dependency installation..."
            npm ci

      # Step 4: Commit Updated Dependencies
      - name: Commit Updated Dependencies
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "Add missing dependency: @vitejs/plugin-react [CI]"
          git push origin ${{ github.event.inputs.branch }}

      # Step 5: Build React App
      - name: Build React App
        run: npm run build

      # Step 6: Start Local Server to Serve the React App
      - name: Start Local Server
        run: |
          npm install -g serve
          serve -s dist -l 5000 &
        env:
          NODE_ENV: production

      # Step 7: Install and Run Ngrok
      - name: Install and Run Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list >/dev/null
          sudo apt update && sudo apt install ngrok
          nohup ngrok http 5000 > ngrok.log 2>&1 &
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      # Step 8: Wait for Ngrok and Output Public URL
      - name: Wait for Ngrok
        run: |
          for i in {1..10}; do
            NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
            if [[ "$NGROK_URL" == http* ]]; then
              echo "Ngrok URL: $NGROK_URL"
              echo "::set-output name=ngrok_url::$NGROK_URL"
              exit 0
            fi
            echo "Waiting for Ngrok to start..."
            sleep 5
          done
          echo "Ngrok failed to start" && exit 1
